#!/bin/bash
#
# Script to complete the post-install process on first FBX boot.

### BEGIN INIT INFO
# Provides:          first-run
# Default-Start:     1 2
# Required-Start:    2
# Required-Stop:
# Default-Stop:
# Short-Description: Finish FBX install on DreamPlug
### END INIT INFO

function tweak-kernel {
    # Update the kernel unless requested otherwise.

    if [ -e /var/freedombox/dont-tweak-kernel ]
    then
        rm /var/freedombox/dont-tweak-kernel
    else
        kernel_version="$(/bin/ls $mountpoint/boot/vmlinuz-*-kirkwood | sort -rn | head -n1 | sed s#$mountpoint/boot/vmlinuz-##)"

        mount -t proc proc /proc
        flash-kernel $kernel_version
        umount /proc
    fi
}

function wifi-ap-setup {
    # configure wireless access point with spinifex's prebuilt firmware

    sleep 30    # wait for dhcp

    wget -O /tmp/marvell_wifi_firmware.tar.gz http://www.spinifex.com.au/plugs/downloads/dreamplug/marvell_wifi_firmware.tar.gz
    tar -C /tmp -zxf /tmp/marvell_wifi_firmware.tar.gz
    mkdir -p /lib/firmware/mrvl
    cp /tmp/lib/firmware/mrvl/* /lib/firmware/mrvl
}

function create-keys {
    echo "Creating Keys."
    echo "Well, not really."
}

function remove-self {
    rm /etc/init.d/first-run
    rm /etc/rc1.d/S01first-run
    rm /etc/rc2.d/S01first-run
}

tweak-kernel
sleep 30    # wait for dhcp
wifi-ap-setup
create-keys
remove-self
echo "Kernel flashed.  Rebooting."
reboot
