#!/usr/bin/python

import crypt
import os
import subprocess
import sys

def runcmd(argv, stdin='', ignore_fail=False, **kwargs):
    p = subprocess.Popen(argv, stdin=subprocess.PIPE, 
                         stdout=subprocess.PIPE, stderr=subprocess.PIPE, 
                         **kwargs)
    out, err = p.communicate(stdin)
    if p.returncode != 0:
        msg = 'command failed: %s\n%s\n%s' % (argv, out, err)
        if not ignore_fail:
            raise Exception(msg)
    return out

print 'Customizing freedombox'

rootdir = sys.argv[1]

# Create a fboxlite account.
runcmd(['chroot', rootdir, 'adduser', '--gecos', 'fbx',
        '--disabled-password', 'fbx'])
encrypted = crypt.crypt('frdm', '..')
runcmd(['chroot', rootdir, 'usermod', '-p', encrypted, 'fbx'])

#Create all projects

runcmd(['chroot', rootdir, 'git', 'clone', 
        'git://github.com/NickDaly/Plinth.git', 
        '/home/fbx/plinth'])

runcmd(['chroot', rootdir, 'git', 'clone', 
        'git://github.com/jvasile/freedombox-privoxy', 
        '/home/fbx/freedombox-privoxy'])

runcmd(['chroot', rootdir, 'git', 'clone', 
        'git://github.com/jvasile/withsqlite.git', 
        '/home/fbx/withsqlite'])

runcmd(['chroot', rootdir, 'hg', 'clone', 
        'https://hg@bitbucket.org/nickdaly/plugserver', 
        '/home/fbx/plugserver'])

runcmd(['chroot', rootdir, 'chown', '-R', 
        '1000:1000', 
        '/home/fbx'])