#!/bin/bash

# Ensure git\VBoxManage  is installed
# Get latest vmdebootstrap code
# Get latest python-cliapp code
# Run vmdebootstrap script to create image
# Convert image to vdi hard drive

# don't tolerate errors.
set -e

basedir=`pwd`
IMAGE=$1

# Get latest vmdebootstrap code
rm -rf vmdebootstrap
git clone git://gitorious.org/~nickdaly/vmdebootstrap/nickdalys-vmdebootstrap.git vmdebootstrap

# Run vmdebootstrap script to create image

sudo ./vmdebootstrap/vmdebootstrap \
    --log freedombox.log --log-level debug \
    --image $IMAGE.img --hostname freedombox --size 1G --verbose --enable-dhcp \
    --package ssh --package apache2 --package git --package mercurial \
	--package build-essential --package checkinstall \
    --package python-simplejson \
	--mirror http://ftp.uk.debian.org/debian/ --package pandoc \
    --package python-cheetah --package python-argparse \
	--customize=$basedir/freedombox-customize --root-password=freedom \
    --arch=i386 --distribution=wheezy

# Convert image to vdi hard drive
VBoxManage convertdd $IMAGE.img $IMAGE.vdi

# Clean up
rm -rf vmdebootstrap
sudo rm -rf python-cliapp

#mkdir testing
#sudo mount -o loop,offset=1048576 freedombox.img testing/
#sudo umount testing/
