#!/bin/bash

# Ensure git\VBoxManage  is installed
# Get vmdebootstrap code
# Run vmdebootstrap script to create image
# Convert image to vdi hard drive

basedir=`pwd`

# Get vmdebootstrap code
rm -rf vmdebootstrap
git clone git://gitorious.org/vmdebootstrap/vmdebootstrap.git

# Run vmdebootstrap script to create image
sudo ./vmdebootstrap/vmdebootstrap --log freedombox.log --log-level debug --image freedombox.img --hostname freedombox \
	--size 1G --verbose --enable-dhcp --package ssh --package apache2 --package git --package mercurial \
	--package build-essential --package checkinstall --package python-simplejson \
	--mirror http://ftp.uk.debian.org/debian/ --package pandoc --package python-cheetah \
	--package python-argparse \
	--customize=$basedir/freedombox-customize --root-password=password1 --arch=i386

# Convert image to vdi hard drive
VBoxManage convertdd freedombox.img freedombox.vdi

#mkdir testing
#sudo mount -o loop,offset=1048576 freedombox.img testing/
#sudo umount testing/