'\" t
.\"     Title: passwd-in-image
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 06/13/2017
.\"    Manual: FreedomBox Manual
.\"    Source: 0.8
.\"  Language: English
.\"
.TH "PASSWD\-IN\-IMAGE" "1" "06/13/2017" "0\&.8" "FreedomBox Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
vagrant-package \- Convert VirtualBox disk image into Vagrant box
.SH "SYNOPSIS"
.HP \w'\fBvagrant\-package\fR\ 'u
\fBvagrant\-package\fR [\fBimage\fR] [\fB\-\-output\fR] [\fB\-h,\ \fR\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
FreedomBox is a community project to develop, design and promote personal servers running free software for private, personal communications\&. It is a networking appliance designed to allow interfacing with the rest of the Internet under conditions of protected privacy and data security\&. It hosts applications such as blog, wiki, website, social network, email, web proxy and a Tor relay on a device that can replace a wireless router so that data stays with the users\&.
.PP
FreedomMaker is a tool to build FreedomBox images for various single board computers, virtual machines and general purpose computers\&.
.PP
Vagrant Package script lets you convert a Virtualbox disk image into a Vagrant box\&.
.SH "OPTIONS"
.PP
\fBimage\fR
.RS 4
Disk image file (\&.vdi) to be converted
.RE
.PP
\fB\-\-output\fR
.RS 4
Path of the output vagrant box file (default: package\&.box)
.RE
.SH "EXAMPLES"
.PP
\fBExample\ \&1.\ \&change password for a user\fR
.sp
.if n \{\
.RS 4
.\}
.nf
$ vagrant\-package freedom\-maker\-beaglebone\&.vdi \-\-output
      beaglebone\&.box 
.fi
.if n \{\
.RE
.\}
.PP
Convert VirtualBox disk image into Vagrant box
.SH "BUGS"
.PP
See the
\m[blue]\fBFreedom\-maker issue tracker\fR\m[]\&\s-2\u[1]\d\s+2
for a full list of known issues and TODO items\&.
.SH "AUTHOR"
.PP
Freedom\-Maker Developers
.SH "NOTES"
.IP " 1." 4
Freedom-maker issue tracker
.RS 4
\%https://github.com/freedombox/freedom-maker/issues
.RE
